apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
  labels:
    app: movies-api
spec:
  selector:
    matchLabels:
      app: movies-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: movies-api
    spec:
      containers:
      - name: movies-api
        image: vishnuprabhas/movies:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "64Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
